language: clojure

jdk:
  - oraclejdk8

sudo: false

script: CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --coveralls

after_script:
  - curl -F 'json_file=@target/coverage/coveralls.json' https://coveralls.io/api/v1/jobs

notifications:
  email:
    on_failure: change
